#ifndef PHSC138_CONFIG_H
#define PHSC138_CONFIG_H


#define TAPPING_TERM 200 // Tap dance tap limit
//#define LCPO_KEYS KC_LCTL, KC_LSFT, KC_LBRC
//#define RCPC_KEYS KC_RCTL, KC_LSFT, KC_RBRC
//#define LAPO_KEYS KC_LALT, KC_TRNS, KC_LBRC
//#define RAPC_KEYS KC_RALT, KC_TRNS, KC_RBRC


#endif
